export interface GlobeCity {
  name: string;
  country: string;
  timeZone: string;
  standardUtcOffsetMinutes: number;
  latitude: number;
  longitude: number;
  priority: number;
}

export const CALIBRATION_CITIES:
  GlobeCity[] = [
    {
      name: 'Pago Pago',
      country: 'American Samoa',
      timeZone: 'Pacific/Pago_Pago',
      standardUtcOffsetMinutes: -660,
      latitude: -14.275632,
      longitude: -170.702036,
      priority: 7,
    },
    {
      name: 'Honolulu',
      country: 'United States',
      timeZone: 'Pacific/Honolulu',
      standardUtcOffsetMinutes: -600,
      latitude: 21.306944,
      longitude: -157.858337,
      priority: 8,
    },
    {
      name: 'Taiohae',
      country: 'French Polynesia',
      timeZone: 'Pacific/Marquesas',
      standardUtcOffsetMinutes: -570,
      latitude: -8.91175,
      longitude: -140.100449,
      priority: 6,
    },
    {
      name: 'Anchorage',
      country: 'United States',
      timeZone: 'America/Anchorage',
      standardUtcOffsetMinutes: -540,
      latitude: 61.218056,
      longitude: -149.900284,
      priority: 7,
    },
    {
      name: 'Los Angeles',
      country: 'United States',
      timeZone: 'America/Los_Angeles',
      standardUtcOffsetMinutes: -480,
      latitude: 34.0536909,
      longitude: -118.242766,
      priority: 10,
    },
    {
      name: 'Denver',
      country: 'United States',
      timeZone: 'America/Denver',
      standardUtcOffsetMinutes: -420,
      latitude: 39.7392364,
      longitude: -104.984862,
      priority: 9,
    },
    {
      name: 'Chicago',
      country: 'United States',
      timeZone: 'America/Chicago',
      standardUtcOffsetMinutes: -360,
      latitude: 41.8755616,
      longitude: -87.6244212,
      priority: 10,
    },
    {
      name: 'New York',
      country: 'United States',
      timeZone: 'America/New_York',
      standardUtcOffsetMinutes: -300,
      latitude: 40.7127281,
      longitude: -74.0060152,
      priority: 10,
    },
    {
      name: 'Caracas',
      country: 'Venezuela',
      timeZone: 'America/Caracas',
      standardUtcOffsetMinutes: -240,
      latitude: 10.5060934,
      longitude: -66.9146008,
      priority: 8,
    },
    {
      name: "St. John's",
      country: 'Canada',
      timeZone: 'America/St_Johns',
      standardUtcOffsetMinutes: -210,
      latitude: 47.5646794,
      longitude: -52.7066964,
      priority: 7,
    },
    {
      name: 'Sao Paulo',
      country: 'Brazil',
      timeZone: 'America/Sao_Paulo',
      standardUtcOffsetMinutes: -180,
      latitude: -23.5506507,
      longitude: -46.6333824,
      priority: 10,
    },
    {
      name: 'Nuuk',
      country: 'Greenland',
      timeZone: 'America/Nuuk',
      standardUtcOffsetMinutes: -120,
      latitude: 64.1767049,
      longitude: -51.7361444,
      priority: 7,
    },
    {
      name: 'Praia',
      country: 'Cape Verde',
      timeZone: 'Atlantic/Cape_Verde',
      standardUtcOffsetMinutes: -60,
      latitude: 14.9162811,
      longitude: -23.5095095,
      priority: 7,
    },
    {
      name: 'Accra',
      country: 'Ghana',
      timeZone: 'Africa/Accra',
      standardUtcOffsetMinutes: 0,
      latitude: 5.5571096,
      longitude: -0.2012376,
      priority: 10,
    },
    {
      name: 'Lagos',
      country: 'Nigeria',
      timeZone: 'Africa/Lagos',
      standardUtcOffsetMinutes: 60,
      latitude: 6.4550575,
      longitude: 3.3941795,
      priority: 10,
    },
    {
      name: 'Johannesburg',
      country: 'South Africa',
      timeZone: 'Africa/Johannesburg',
      standardUtcOffsetMinutes: 120,
      latitude: -26.205,
      longitude: 28.049722,
      priority: 9,
    },
    {
      name: 'Nairobi',
      country: 'Kenya',
      timeZone: 'Africa/Nairobi',
      standardUtcOffsetMinutes: 180,
      latitude: -1.2890006,
      longitude: 36.8172812,
      priority: 10,
    },
    {
      name: 'Tehran',
      country: 'Iran',
      timeZone: 'Asia/Tehran',
      standardUtcOffsetMinutes: 210,
      latitude: 35.6892523,
      longitude: 51.3896004,
      priority: 8,
    },
    {
      name: 'Dubai',
      country: 'United Arab Emirates',
      timeZone: 'Asia/Dubai',
      standardUtcOffsetMinutes: 240,
      latitude: 25.0742823,
      longitude: 55.1885624,
      priority: 10,
    },
    {
      name: 'Kabul',
      country: 'Afghanistan',
      timeZone: 'Asia/Kabul',
      standardUtcOffsetMinutes: 270,
      latitude: 34.5269503,
      longitude: 69.1850584,
      priority: 7,
    },
    {
      name: 'Karachi',
      country: 'Pakistan',
      timeZone: 'Asia/Karachi',
      standardUtcOffsetMinutes: 300,
      latitude: 24.8546842,
      longitude: 67.0207055,
      priority: 9,
    },
    {
      name: 'Mumbai',
      country: 'India',
      timeZone: 'Asia/Kolkata',
      standardUtcOffsetMinutes: 330,
      latitude: 19.054999,
      longitude: 72.8692035,
      priority: 10,
    },
    {
      name: 'Kathmandu',
      country: 'Nepal',
      timeZone: 'Asia/Kathmandu',
      standardUtcOffsetMinutes: 345,
      latitude: 27.708317,
      longitude: 85.3205817,
      priority: 8,
    },
    {
      name: 'Dhaka',
      country: 'Bangladesh',
      timeZone: 'Asia/Dhaka',
      standardUtcOffsetMinutes: 360,
      latitude: 23.7643863,
      longitude: 90.3890144,
      priority: 9,
    },
    {
      name: 'Yangon',
      country: 'Myanmar',
      timeZone: 'Asia/Yangon',
      standardUtcOffsetMinutes: 390,
      latitude: 16.7967129,
      longitude: 96.1609916,
      priority: 8,
    },
    {
      name: 'Bangkok',
      country: 'Thailand',
      timeZone: 'Asia/Bangkok',
      standardUtcOffsetMinutes: 420,
      latitude: 13.7524938,
      longitude: 100.4935089,
      priority: 9,
    },
    {
      name: 'Singapore',
      country: 'Singapore',
      timeZone: 'Asia/Singapore',
      standardUtcOffsetMinutes: 480,
      latitude: 1.357107,
      longitude: 103.8194992,
      priority: 10,
    },
    {
      name: 'Eucla',
      country: 'Australia',
      timeZone: 'Australia/Eucla',
      standardUtcOffsetMinutes: 525,
      latitude: -31.6768407,
      longitude: 128.8865164,
      priority: 6,
    },
    {
      name: 'Tokyo',
      country: 'Japan',
      timeZone: 'Asia/Tokyo',
      standardUtcOffsetMinutes: 540,
      latitude: 35.6768601,
      longitude: 139.7638947,
      priority: 10,
    },
    {
      name: 'Adelaide',
      country: 'Australia',
      timeZone: 'Australia/Adelaide',
      standardUtcOffsetMinutes: 570,
      latitude: -34.9281805,
      longitude: 138.5999312,
      priority: 8,
    },
    {
      name: 'Brisbane',
      country: 'Australia',
      timeZone: 'Australia/Brisbane',
      standardUtcOffsetMinutes: 600,
      latitude: -27.4689623,
      longitude: 153.0235009,
      priority: 9,
    },
    {
      name: 'Lord Howe',
      country: 'Australia',
      timeZone: 'Australia/Lord_Howe',
      standardUtcOffsetMinutes: 630,
      latitude: -31.5540166,
      longitude: 159.0856256,
      priority: 6,
    },
    {
      name: 'Honiara',
      country: 'Solomon Islands',
      timeZone: 'Pacific/Guadalcanal',
      standardUtcOffsetMinutes: 660,
      latitude: -9.4310769,
      longitude: 159.9552552,
      priority: 7,
    },
    {
      name: 'Auckland',
      country: 'New Zealand',
      timeZone: 'Pacific/Auckland',
      standardUtcOffsetMinutes: 720,
      latitude: -36.852095,
      longitude: 174.7631803,
      priority: 9,
    },
    {
      name: 'Waitangi',
      country: 'New Zealand',
      timeZone: 'Pacific/Chatham',
      standardUtcOffsetMinutes: 765,
      latitude: -43.95353,
      longitude: -176.55973,
      priority: 6,
    },
    {
      name: "Nuku'alofa",
      country: 'Tonga',
      timeZone: 'Pacific/Tongatapu',
      standardUtcOffsetMinutes: 780,
      latitude: -21.1343401,
      longitude: -175.201808,
      priority: 7,
    },
    {
      name: 'Kiritimati',
      country: 'Kiribati',
      timeZone: 'Pacific/Kiritimati',
      standardUtcOffsetMinutes: 840,
      latitude: 1.872,
      longitude: -157.3842085,
      priority: 7,
    },
  ];